from app.extensions import db
from app.models.product import Product


def seed_products():
    if Product.query.first():
        print("✅ Products already seeded. Skipping.")
        return

    products = [
        Product(
            name="2 Layer Effortless Cleansing Balm",
            suitable_for="Semua jenis kulit",
            key_ingredient="Elderberry, Mugwort Cica, Watermelon Extract, Blueberry Extract, Centella Asiatica Extract, Artemisia Vulgaris Extract, Sambucus nigra fruit extract",
            benefit="Membersihkan dan mengangkat sisa make up wajah secara menyeluruh dalam 15 detik, Membersihkan make up pada wajah tanpa membuat kulit terasa kering, Kulit lebih halus dan tidak menyumbat pori pori pada wajah, Membantu menghaluskan dan menenangkan kulit",
            product_category_id=3,
            brand_id=11,
            product_type_detail_id=1,
            ingredient_id=12,
            skin_problem_id=3,
        ),
        Product(
            name="Milk Cleanser Bengkuang",
            suitable_for="Semua jenis kulit",
            key_ingredient="Ekstrak Bengkuang, Ekstrak Sunflower",
            benefit="Susu Pembersih untuk kulit normal, mengandung bahan alami Ekstrak Bengkuang untuk kulit wajah tampak lebih cerah dan Ekstrak Sun Flower untuk merawat elastisitas atau kelenturan kulit wajah",
            product_category_id=3,
            brand_id=7,
            product_type_detail_id=2,
            ingredient_id=12,
            skin_problem_id=3,
        ),
        Product(
            name="Beauty Chamomile & Olive Deep Cleansing Oil",
            suitable_for="Semua jenis kulit",
            key_ingredient="Olive oil, Chamomile Extract, dan Vitamin E",
            benefit="Kaya akan antioksidant, anti-inflamasi, soothe dan moisterize agent, membantu meringankan iritasi dan mempercepat penyembuhan luka atau bekas jerawat pada kulit, meringankan aczema, psoriosis, dan prutus atau gatal, Mengangkat/membersihkan make up lebih bersih",
            product_category_id=3,
            brand_id=8,
            product_type_detail_id=3,
            ingredient_id=12,
            skin_problem_id=3,
        ),
        Product(
            name="Calm Down Gentle Micellar Water",
            suitable_for="Semua jenis kulit, termasuk kulit sensitif",
            key_ingredient="Calm Down®, Calendula, Madagascar Centella Asiatica",
            benefit="Menghapus sunscreen, makeup waterproof, kotoran & debu hingga bersih tanpa membuat kulit kering atau merusak skin barrier",
            product_category_id=3,
            brand_id=1,
            product_type_detail_id=4,
            ingredient_id=8,
            skin_problem_id=3,
        ),
        Product(
            name="N-Dose+ 2.0 Intensive Brightening Facial Wash",
            suitable_for="Semua jenis kulit, kulit kusam",
            key_ingredient="Amino Cleanser, Niacinamide, Oxy229® , Hyalucomplex-10",
            benefit="Membersihkan kulit wajah secara gentle, Membantu mencerahkan kulit,  Membantu proses pengangkatan sel kulit mati",
            product_category_id=3,
            brand_id=3,
            product_type_detail_id=5,
            ingredient_id=12,
            skin_problem_id=3,
        ),
        Product(
            name="Pure Gentle Cleanser",
            suitable_for="Kulit sensitif berjerawat, kulit normal dan kombinasi",
            key_ingredient="Sodium PCA, Plant Based Surfactant",
            benefit="Membersihkan wajah dari kotoran dan minyak berlebih, menjaga kelembapan kulit, membantu melindungi skin barrier",
            product_category_id=3,
            brand_id=4,
            product_type_detail_id=6,
            ingredient_id=9,
            skin_problem_id=1,
        ),
        Product(
            name="9X Hyaluronic Acid Gentle Cleansing Mousse",
            suitable_for="Semua jenis kulit",
            key_ingredient="3X Ceramide, 9X Hyaluronic Acid, Niacinamide",
            benefit="Membersihkan wajah dengan lembut, Membersihkan minyak berlebih , Mencegah timbulnya jerawat, Membuat kulit wajah bersih dan lembut",
            product_category_id=3,
            brand_id=5,
            product_type_detail_id=7,
            ingredient_id=9,
            skin_problem_id=2,
        ),
        Product(
            name="Supple Power Hyaluronic9+Onsen Moisture Bomb Gel",
            suitable_for="Semua jenis kulit, khususnya kulit kering atau kusam",
            key_ingredient="Onsen Sui Water, 9 Type Hyaluronic, Vitamin B5/ Panthenol, Ceramide Complex (NP/AP/EOP), Chondrus Crispus (Carrageenan) Extract",
            benefit="Meremajakan kulit, membantu meningkatkan produksi kolagen, mencegah tanda penuaan dini agar kulit tetap sehat & kenyal sepanjang hari",
            product_category_id=2,
            brand_id=1,
            product_type_detail_id=8,
            ingredient_id=10,
            skin_problem_id=3,
        ),
        Product(
            name="Luxurious Soft Hydrating Moisturizer",
            suitable_for="Semua jenis kulit",
            key_ingredient="Synoxyl® AZ, AstaMacadamia, dan Madecassoside",
            benefit="Meredakan kemerahan akibat sinar UV, mengembalikan keseimbangan alami kulit, Mengunci kelembapan untuk hidrasi mendalam dan tahan lama, Menjaga elastisitas kulit sekaligus memperkuat lapisan pelindungnya, memberikan tampilan kulit yang lebih sehat dan bercahaya",
            product_category_id=2,
            brand_id=9,
            product_type_detail_id=9,
            ingredient_id=14,
            skin_problem_id=2,
        ),
        Product(
            name="Physical Sunscreen SPF 50 PA++++",
            suitable_for="Kulit sensitif",
            key_ingredient="Zinc Oxide dan Titanium Oxide",
            benefit="Menangkal sinar UVA UVB, blue light, dan radikal bebas dari polusi yang disebabkan oleh paparan sinar matahari, membantu menjaga keseimbangan skin microbiome sehingga menjaga kekuatan skin barrier",
            product_category_id=1,
            brand_id=12,
            product_type_detail_id=10,
            ingredient_id=8,
            skin_problem_id=2,
        ),
        Product(
            name="Sunfriends Sunscreen Gel Noncomedogenic SPF 50 PA++++",
            suitable_for="Semua jenis kulit",
            key_ingredient="Matcha, Cica, Betaine",
            benefit="Perlindungan UV, cepat menyerap, ringan, noncomedogenic, dan tidak ada whitecast",
            product_category_id=1,
            brand_id=11,
            product_type_detail_id=11,
            ingredient_id=7,
            skin_problem_id=1,
        ),
        Product(
            name="Luxurious Perfecting Sunscreen",
            suitable_for="Semua jenis kulit",
            key_ingredient="Pollustop, Centella Asiatica, Black Tea, D-Panthenol, Astaxanthin",
            benefit="Memberikan perlindungan optimal dari sinar matahari, menangkal polusi, mengurangi efek buruk sinar matahari",
            product_category_id=1,
            brand_id=9,
            product_type_detail_id=12,
            ingredient_id=7,
            skin_problem_id=3,
        ),
        Product(
            name="All Skin Types Gloze up Night Pack",
            suitable_for="Semua jenis kulit",
            key_ingredient="Tranexamic Acid, Lactic Acid, Vitamin C, Niacinamide, Hexylresorcinol, Vitamin E (Tocopherol)",
            benefit="Membantu mencerahkan dan meratakan warna kulit, mengurangi noda hitam dan tanda-tanda penuaan, menghidrasi dan menjaga kelembapan kulit, melembutkan kulit dan menjaga elastisitas, membuat kulit tetap kenyal dan terhidrasi",
            product_category_id=2,
            brand_id=13,
            product_type_detail_id=8,
            ingredient_id=1,
            skin_problem_id=3,
        ),
        Product(
            name="Glycolic Brightening Cleanser",
            suitable_for="Kulit normal",
            key_ingredient="Glycolic, D-Panthenol, Allantoin",
            benefit="Mencerahkan kulit wajah, mengangkat sel-sel kulit mati dengan lembut, melembapkan kulit wajah, menyamarkan noda hitam",
            product_category_id=3,
            brand_id=9,
            product_type_detail_id=6,
            ingredient_id=1,
            skin_problem_id=3,
        ),
        Product(
            name="Protective Tinted Mineral Matte Sunscreen",
            suitable_for="Kulit Berminyak",
            key_ingredient="Rosmarinus Officinalis (Rosemary), Lactic Acid, Leaf Extract, Chrysin, Palmitoyl Tetrapeptide-7",
            benefit="Memberikan perlindungan dari sinar UV, membuat warna kulit lebih merata, dan membantu menyamarkan noda pada kulit",
            product_category_id=1,
            brand_id=14,
            product_type_detail_id=10,
            ingredient_id=1,
            skin_problem_id=3,
        ),
        Product(
            name="Skinsitive Ultracalm Tender Care Skin Barrier Moisturizer",
            suitable_for="Kulit kering dan sensitif",
            key_ingredient="Ceramide Complex, Allantoin, Panthenol, Niacinamide, Shea Butter, AQUAXYL & Squalane",
            benefit="Memperbaiki skin barrier dan menenangkan kulit teriritasi, melembapkan sekaligus memperkuat fungsi pertahanan kulit sehingga kulit menjadi lembap, kenyal, dan sehat",
            product_category_id=2,
            brand_id=15,
            product_type_detail_id=8,
            ingredient_id=2,
            skin_problem_id=2,
        ),
        Product(
            name="Java Black Tea Soothing Gel Cleanser",
            suitable_for="Semua jenis kulit",
            key_ingredient="Java Back tea, Cica, Soybean, Lychee Extract, Vitamin B5, Allantoin, Tea Tree Leaf Extract",
            benefit="Membersihkan noda dari pori-pori, minyak berlebih, make-up, dan bersihkan sisa kotoran lainnya pada wajah, menjadikan kulit lebih bersih, segar, dan tenang",
            product_category_id=3,
            brand_id=16,
            product_type_detail_id=6,
            ingredient_id=2,
            skin_problem_id=1,
        ),
        Product(
            name="The Great Shield SPF 50 PA++++",
            suitable_for="Semua jenis kulit",
            key_ingredient="Allantoin, Chamomile Flower Extract, Sodium Hyaluronate (HA), 3-O-Ethyl Ascorbic Acid, Silica",
            benefit="Melindungi kulit dari paparan sinar UVA dan UVB, membantu menenangkan kulit, membantu mencegah tampilan penuaan dini, serta menyamarkan tampilan pori-pori, merawat elastisitas kulit agar tampak lebih sehat",
            product_category_id=1,
            brand_id=17,
            product_type_detail_id=12,
            ingredient_id=2,
            skin_problem_id=1,
        ),
        Product(
            name="Nature Daily Aloe Hydramild Multifunction Gel",
            suitable_for="Semua jenis kulit",
            key_ingredient="Aloe Vera Extract, Allantoin, Biosaccharide-Gum, Beta Glucon",
            benefit="Melembapkan kulitmu secara optimal, merawat elastisitas dan kesegaran kulit, menyejukkan kulit, membantu merawat kulit yang merah dari polusi dan sengatan matahari",
            product_category_id=2,
            brand_id=18,
            product_type_detail_id=8,
            ingredient_id=3,
            skin_problem_id=2,
        ),
        Product(
            name="Cica + Aloe Low pH Hydramild Facial Wash",
            suitable_for="Semua jenis kulit",
            key_ingredient="Centella Asiatica, Panthenol, Aloe Vera",
            benefit="Mengurangi kemerahan, cegah iritasi, dan mengembalikan kelembaban kulit",
            product_category_id=3,
            brand_id=18,
            product_type_detail_id=6,
            ingredient_id=3,
            skin_problem_id=2,
        ),
        Product(
            name="Hydrasoothe Sunscreen Gel",
            suitable_for="Semua jenis kulit terutama kulit berjerawat, berminyak, dan kombinasi",
            key_ingredient="Royal jelly, Resveratrol, Green tea, Ectoin",
            benefit="Melindungi kulit dari efek negatif sinar UV A & UV B dan menutrisi kulit",
            product_category_id=1,
            brand_id=19,
            product_type_detail_id=11,
            ingredient_id=3,
            skin_problem_id=1,
        ),
        Product(
            name="YSB Glow Concentrate Treatment 2% Alpha Arbutin + Multi Probiome + Beta Carotene",
            suitable_for="Kulit wajah yang kering dan kusam",
            key_ingredient="Alpha Arbutin, Multi Probiome, dan Beta Carotene",
            benefit="Membantu mencerahkan dan menyamarkan post-inflammatory hyperpigmentation (PIH) atau bekas jerawat kehitaman",
            product_category_id=2,
            brand_id=17,
            product_type_detail_id=8,
            ingredient_id=4,
            skin_problem_id=3,
        ),
        Product(
            name="Radiance Double Refresh Brightening SkinBubble",
            suitable_for="Kulit normal",
            key_ingredient="Alpha Arbutin, Greenth, Micro Scrub, dan Microbiome",
            benefit="Membantu mencerahkan kulit, Membantu mengatasi permasalahan kulit seperti hiperpigmentasi, bintik hitam dan warna kulit yang tidak merata, Membantu membersihkan pori-pori sembari tetap menjaga kelembapan kulit",
            product_category_id=3,
            brand_id=20,
            product_type_detail_id=6,
            ingredient_id=4,
            skin_problem_id=3,
        ),
        Product(
            name="Antioxidant Suncream",
            suitable_for="Semua jenis kulit",
            key_ingredient="Salmon DNA, Titanium Dioxide, Niacinamide, Alpha Arbutin",
            benefit="Mengurangi pigmentasi wajah, melembabkan kulit, melindungi kulit dari UV & paparan sinar matahari, menyamarkan bekas jerawat",
            product_category_id=1,
            brand_id=13,
            product_type_detail_id=12,
            ingredient_id=4,
            skin_problem_id=3,
        ),
        Product(
            name="Papua Red Fruit Plumping Cream",
            suitable_for="Semua jenis kulit",
            key_ingredient="LUMERA™ Red Fruit Extract, Bakuchiol, Peptide COmplex, Vitmain E, Camellia Japonica Oil",
            benefit="Merevitalisasi kulit yang kering & dehidrasi secara instan, mengurangi tampilan garis halus & kerutan secara instan, menjaga elastisitas & keremajaan kulit",
            product_category_id=2,
            brand_id=16,
            product_type_detail_id=9,
            ingredient_id=5,
            skin_problem_id=3,
        ),
        Product(
            name="Calm My Acne Sunscreen Moisturiser",
            suitable_for="Dapat digunakan untuk semua jenis kulit namun sangat cocok untuk kulit berjerawat, kulit berminyak, kulit kombinasi, dan kulit sensitif sekalipun",
            key_ingredient="Bakuchiol, Pionin, Canadian Willoherb, Ectoin",
            benefit="Melindungi skin barrier dari paparan sinar UV A & UV B, bluelight, serta polusi",
            product_category_id=2,
            brand_id=16,
            product_type_detail_id=10,
            ingredient_id=5,
            skin_problem_id=1,
        ),
        Product(
            name="Triple Care Oil Control Acne Calm Moisturizer",
            suitable_for="Kulit berjerawat",
            key_ingredient="Trikenol Plus, Encapsulated Salicylic Acid, Succinic Acid, Madecassoside Pure, Mangosteen Extract",
            benefit="Melembabkan secara instan, meredakan jerawat, menenangkan kulit berjerawat, meredakan kemerahan, mengontrol timbulnya jerawat",
            product_category_id=2,
            brand_id=2,
            product_type_detail_id=8,
            ingredient_id=6,
            skin_problem_id=1,
        ),
        Product(
            name="Matcha Oat Gentle Gel Cleanser",
            suitable_for="Semua jenis kulit",
            key_ingredient="Matcha, Oat Extract, Heart Leaf, Licorice, Collagen, Kiwi Seed Extract, Allantoin, Salicylic Acid",
            benefit="Menghidrasi, formula tidak mengeringkan, menyegarkan kulit, melindungi kulit dari radikal bebas, membersihkan kulit secara mendalam, tingkat pH 5,5-6,5",
            product_category_id=3,
            brand_id=11,
            product_type_detail_id=6,
            ingredient_id=6,
            skin_problem_id=1,
        ),
        Product(
            name="Calm Down! Skinpair R-Cover Cream",
            suitable_for="Semua jenis kulit, terutama kulit sensitif",
            key_ingredient="CalmDown® by Somethinc®, Madagascar Centella Asiatica, Murumuru butter, Encapsulated Ceramide, Panthenol, Korean Mugwort",
            benefit="Melindungi barrier kulit dengan menghidrasi secara maksimal sepanjang hari, Menghidrasi & menenangkan kulit secara instan",
            product_category_id=2,
            brand_id=1,
            product_type_detail_id=9,
            ingredient_id=7,
            skin_problem_id=2,
        ),
        Product(
            name="Acne Clear Foam Facial Wash",
            suitable_for="Untuk semua jenis kulit, terutama acne prone skin",
            key_ingredient="Centella Asiatica Extract, Niacinamide, Salicylic Acid, Glutathione, Mild surfactant/SLS Free",
            benefit="Membantu membuat kulit wajah bersih dari debu & polusi, membantu merawat kulit berjerawat",
            product_category_id=3,
            brand_id=22,
            product_type_detail_id=7,
            ingredient_id=7,
            skin_problem_id=1,
        ),
        Product(
            name="CICA RES-Q10 - AdapTint Sun Shield",
            suitable_for="Semua jenis kulit",
            key_ingredient="Centella Asiatica",
            benefit="Memberikan perlindungan maksimal dari 5 broad spectrum (UVA, UVB, Bluelight, Infrared, Polusi hingga PM2.5), serta sebagai skin adapting sunscreen, meratakan warna kulit secara instan pada semua jenis tone kulit",
            product_category_id=1,
            brand_id=23,
            product_type_detail_id=10,
            ingredient_id=7,
            skin_problem_id=3,
        ),
        Product(
            name="Kind Watery Moisturizer - Oily",
            suitable_for="Kulit cenderung berminyak",
            key_ingredient="Panthenol, Ceramide, Phytosphingosine, Trehalose, Cholesterol",
            benefit="Menjaga fungsi barrier kulit, menghidrasi, melembabkan",
            product_category_id=2,
            brand_id=24,
            product_type_detail_id=8,
            ingredient_id=8,
            skin_problem_id=1,
        ),
        Product(
            name="Triple Care Facial Gel Cleanser",
            suitable_for="Semua jenis kulit",
            key_ingredient="Oat, Chamomile, Ceramide, Panthenol",
            benefit="Menenangkan, Melembabkan Kulit, Menghilangkan Sel Kulit Mati, Melindungi kulit dari tanda-tanda kerusakan lingkungan yang terlihat, Memperkuat Skin Barrier, Efek Pembersihan Mendalam yang Mencerahkan",
            product_category_id=3,
            brand_id=2,
            product_type_detail_id=6,
            ingredient_id=8,
            skin_problem_id=3,
        ),
        Product(
            name="UV WaterBarrier Sunscreen",
            suitable_for="Semua jenis kulit",
            key_ingredient="Ceramide, Centella Asiatica, Oat",
            benefit="Melindungi barrier kulit dari UVA, UVB, blue light, polusi, radikal bebas, penuaan dini & kerusakan DNA",
            product_category_id=1,
            brand_id=25,
            product_type_detail_id=10,
            ingredient_id=8,
            skin_problem_id=3,
        ),
        Product(
            name="Comfort Zone Soothing Moisturizer",
            suitable_for="Semua jenis kulit",
            key_ingredient="Glycerin, Panthenol (pro-vitamin B5), Bisabolol, Ceramide",
            benefit="Menjaga kesehatan skin barrier, menenangkan, menghidrasi, dan melembabkan",
            product_category_id=2,
            brand_id=26,
            product_type_detail_id=9,
            ingredient_id=9,
            skin_problem_id=3,
        ),
        Product(
            name="Solar Smart UV Protector",
            suitable_for="Kulit normal hingga kering",
            key_ingredient="Niacinamide, Cica, Honey, Glycerin",
            benefit="Melindungi optimal dengan SPF 45 yang menangkal 97.8% UVB, dan PA++++ perlindungan tertinggi terhadap UVA yang dapat memicu hyperpigmentasi dan penuaan dini",
            product_category_id=1,
            brand_id=27,
            product_type_detail_id=11,
            ingredient_id=9,
            skin_problem_id=3,
        ),
        Product(
            name="9x Hyaluronic Acid Emulsion for Normal to Oily Skin",
            suitable_for="Kulit normal cenderung berminyak",
            key_ingredient="Ceramide, Hyaluronic Acid, Centella Asiatica",
            benefit="Menjaga skin barrier tetap kuat, Menghidrasi dan Melembapkan kulit wajah, Menenangkan kulit yang merah atau iritasi",
            product_category_id=2,
            brand_id=5,
            product_type_detail_id=8,
            ingredient_id=10,
            skin_problem_id=2,
        ),
        Product(
            name="Skin Barrier Face Gel Cleanser",
            suitable_for="Kulit Kering, Kulit Normal, Kulit Berminyak dan Cenderung Berjerawat, Kulit Sensitif",
            key_ingredient="Ceramide Complex, Hyaluronic Acid, Beatine, Phytospingosine",
            benefit="Membersihkan kotoran dan minyak berlebih pada kulit wajah",
            product_category_id=3,
            brand_id=6,
            product_type_detail_id=6,
            ingredient_id=10,
            skin_problem_id=1,
        ),
        Product(
            name="White Tea Ultra Light Protective Sun Serum",
            suitable_for="Semua jenis kulit",
            key_ingredient="Java White Tea, Heartleaf Extract, Triple Hyaluronic Acid Complex",
            benefit="Melindungi kulit dari paparan sinar UVA dan UVB, memberikan proteksi terhadap polusi, dan menjaga kelembaban kulit",
            product_category_id=1,
            brand_id=16,
            product_type_detail_id=11,
            ingredient_id=10,
            skin_problem_id=3,
        ),
        Product(
            name="Mugwort Tripeptide Anti-Aging Moisturizer Gel Cream",
            suitable_for="Semua jenis kulit, warna kulit tidak merata, kulit berjerawat, kemerahan, dan teriritasi",
            key_ingredient="Mugwort, Bisabolol, Tripeptide",
            benefit="Ringan dan cepat menyerap, menghidrasi dan melembabkan kulit, meredakan kemerahan, meredakan jerawat, anti-aging, dan menghaluskan kulit",
            product_category_id=2,
            brand_id=11,
            product_type_detail_id=8,
            ingredient_id=11,
            skin_problem_id=2,
        ),
        Product(
            name="Calm Down! Skinpair Bubble Cleanser",
            suitable_for="Semua jenis kulit, terutama kulit sensitif",
            key_ingredient="CalmDown®, 3D Aqua Seal Technology, Panthenol, Heartleaf, Korean Mugwort, Mild Surfactant",
            benefit="Membersihkan debu, sunscreen, makeup & kotoran dari aktivitas sehari-hari tanpa menghilangkan kelembaban, membantu menenangkan kemerahan, memperkuat skin barrier & menjaga kelembaban dengan minimal gesekan di kulit",
            product_category_id=3,
            brand_id=1,
            product_type_detail_id=7,
            ingredient_id=11,
            skin_problem_id=2,
        ),
        Product(
            name="Mugwort Daily Sunscreen",
            suitable_for="Kulit berjerawat",
            key_ingredient="Mugwort, Centella Asiatica/Cica, Panthenol",
            benefit="Melindungi kulit dari sinar matahari dengan SPF 35 PA+++, Mencegah penuaan dini akibat sinar UV, Mencegah iritasi kulit akibat paparan sinar UV, Membantu merawat kulit berjerawat dengan kandungan calming ingredients",
            product_category_id=1,
            brand_id=28,
            product_type_detail_id=10,
            ingredient_id=11,
            skin_problem_id=1,
        ),
        Product(
            name="Skin Barrier Water Cream",
            suitable_for="Semua jenis kulit",
            key_ingredient="Niacinamide, Hyaluronic Acid, Adenosine, Centella Asiatica (CICA), Ceramide, Ekstrak Semangka",
            benefit="Membantu meningkatkan skin barrier, meningkatkan kelembapan kulit, mempertahankan dan mengunci kelembapan agar kulit tampak lebih kenyal",
            product_category_id=2,
            brand_id=6,
            product_type_detail_id=8,
            ingredient_id=12,
            skin_problem_id=3,
        ),
        Product(
            name="Skin Barrier Water Cream",
            suitable_for="Semua jenis kulit",
            key_ingredient="Niacinamide, Hyaluronic Acid, Adenosine, Centella Asiatica (CICA), Ceramide, Ekstrak Semangka",
            benefit="Membantu meningkatkan skin barrier, meningkatkan kelembapan kulit, mempertahankan dan mengunci kelembapan agar kulit tampak lebih kenyal",
            product_category_id=2,
            brand_id=6,
            product_type_detail_id=8,
            ingredient_id=12,
            skin_problem_id=3,
        ),
        Product(
            name="Velvet Sunscreen",
            suitable_for="Kulit normal hingga berminyak",
            key_ingredient="Guaiazulene, Niacinamide",
            benefit="Melindungi kulit dari paparan sinar UV, Mengontrol sebum & minyak berlebih",
            product_category_id=1,
            brand_id=29,
            product_type_detail_id=11,
            ingredient_id=12,
            skin_problem_id=1,
        ),
        Product(
            name="Cica Care Gel Moisturizer",
            suitable_for="Semua jenis kulit",
            key_ingredient="Centella Asiatica, 5x Ceramide, 8x HA, Oat Extract, Phytosqualane",
            benefit="Menghidrasi dan memperkuat skin barrier, Menenangkan kulit berjerawat & sensitif, Tekstur gel yang ringan untuk kulit berminyak, Aman untuk ibu hamil & ibu menyusui",
            product_category_id=2,
            brand_id=30,
            product_type_detail_id=8,
            ingredient_id=13,
            skin_problem_id=1,
        ),
        Product(
            name="Triple Care Facial Gel Cleanser",
            suitable_for="Semua jenis kulit",
            key_ingredient="Oat, Chamomile, Ceramide, Panthenol",
            benefit="Menenangkan, Melembabkan Kulit, Menghilangkan Sel Kulit Mati, Melindungi kulit dari tanda-tanda kerusakan lingkungan yang terlihat, Memperkuat Skin Barrier, Efek Pembersihan Mendalam yang Mencerahkan",
            product_category_id=3,
            brand_id=2,
            product_type_detail_id=6,
            ingredient_id=13,
            skin_problem_id=3,
        ),
        Product(
            name="Oat Probiotic Lightweight Sunscreen",
            suitable_for="Semua jenis kulit termasuk kulit sensitif dan berjerawat",
            key_ingredient="Oat Probiotic, Panthenol, Honey Extract, Centella Asiatica, SPF",
            benefit="Melindungi dari sinar UV dengan SPF 50 dan PA++++, Menjaga kulit tetap sehat dan memperkuat skin barrier",
            product_category_id=1,
            brand_id=31,
            product_type_detail_id=11,
            ingredient_id=13,
            skin_problem_id=3,
        ),
        Product(
            name="Marine Algae Revitalize Bouncing Hydrating Moisturizer",
            suitable_for="Kulit sensitif",
            key_ingredient="Aloe Barbadensis Leaf Water, Niacinamide Snow Algae Powder, Panthenol, Chondrus Crispus Extract Solution",
            benefit="Menghidrasi kulit dari dalam dan memberikan kelembapan secara intensif, Menyamarkan tanda-tanda penuaan dini, Mencerahkan kulit dan membuat kulit tampak lebih muda dan bercahaya, Formula ringan dan mudah menyerap",
            product_category_id=2,
            brand_id=14,
            product_type_detail_id=8,
            ingredient_id=14,
            skin_problem_id=3,
        ),
        Product(
            name="Barrier+ pH Balance Jelly Cleanser",
            suitable_for="Semua jenis kulit",
            key_ingredient="Panthenol, Sage leaf, Oat Kernel",
            benefit="Membersihkan kotoran dan makeup secara mendalam tanpa membuat kulit kering atau tertarik, Menyeimbangkan pH kulit, Melembabkan, menutrisi, dan menjaga level hidrasi kulit",
            product_category_id=3,
            brand_id=32,
            product_type_detail_id=6,
            ingredient_id=14,
            skin_problem_id=3,
        ),
        Product(
            name="Your Skin Bae Glow Concentrate Treatment Polypeptide",
            suitable_for="Semua jenis kulit",
            key_ingredient="Polypeptide, Multi Probiome, Acetyl Glucosamine, dan Red Algae",
            benefit="menjaga kelembapan kulit wajah, membantu menyamarkan garis halus dan kerutan, serta membuat permukaan kulit tampak lebih halus, membantu menjaga kesehatan dan tekstur kulit, membantu menjaga kelembapan kulit sekaligus membuat kulit tampak lebih halus dan sehat",
            product_category_id=2,
            brand_id=17,
            product_type_detail_id=8,
            ingredient_id=15,
            skin_problem_id=3,
        ),
        Product(
            name="Protective Tinted Mineral Glow Sunscreen",
            suitable_for="Kulit Berminyak",
            key_ingredient="Rosmarinus Officinalis (Rosemary), Lactic Acid, Leaf Extract, Chrysin, Palmitoyl Tetrapeptide-7",
            benefit="Memberikan perlindungan dari sinar UV, membuat warna kulit lebih merata, dan membantu menyamarkan noda pada kulit",
            product_category_id=1,
            brand_id=14,
            product_type_detail_id=10,
            ingredient_id=15,
            skin_problem_id=3,
        ),
        Product(
            name="Comfort You Skin Barrier Rehab Facial Wash",
            suitable_for="Kulit kering dan sensitif",
            key_ingredient="Oatmeal (Oat Oil), D-Panthenol, PHA (Gluconolactone), Allantoin",
            benefit="Mengangkat kotoran dan sel-sel kulit mati dengan lembut, serta melembapkan kulit wajah",
            product_category_id=3,
            brand_id=33,
            product_type_detail_id=6,
            ingredient_id=16,
            skin_problem_id=3,
        ),
        Product(
            name="Bee Power Propolis & Manuka Honey Sleeping Mask",
            suitable_for="Semua jenis kulit",
            key_ingredient="Korean Propolis, Manuka Honey, Bee Venom, Trehalose",
            benefit="Memberi kelembaban & nutrisi di malam hari, Menjadikan kulit tampak lebih glowing keesokan pagi dengan minyak yang lebih terkontrol",
            product_category_id=2,
            brand_id=1,
            product_type_detail_id=8,
            ingredient_id=17,
            skin_problem_id=1,
        ),
        Product(
            name="Face Wash",
            suitable_for="Semua jenis kulit",
            key_ingredient="Propolis Extract (Propoelix™), Organic Aloe Vera, Niacinamide (Vitamin B3), Hydrolyzed Algin, Honey, Yogurt, Multivitamins, Inulin",
            benefit="Membersihkan dan hidrasi, kulit cerah berseri, kulit halus dan bernutrisi, memberikan vitalitas dan perlindungan lebih",
            product_category_id=3,
            brand_id=34,
            product_type_detail_id=6,
            ingredient_id=17,
            skin_problem_id=3,
        ),
        Product(
            name="Fresh Skin Barrier Soothing Cream",
            suitable_for="Kulit kemerahan, kulit normal hingga berminyak dan cenderung berjerawat",
            key_ingredient="Sugarcane Squalane, ProVitamin B5, Mugwort, Cica (Centella asiatica), Black Cumin Seed (Habatussauda)",
            benefit="Menenangkan kulit berjerawat & memperkuat skin barrier",
            product_category_id=2,
            brand_id=35,
            product_type_detail_id=8,
            ingredient_id=18,
            skin_problem_id=1,
        ),
        Product(
            name="Algaktiv Optimmunist Hydraplus Milky Facial Wash",
            suitable_for="Semua jenis kulit",
            key_ingredient="Algaktiv Optimmunist, Glycerin, Squalane",
            benefit="Membersihkan kulit tanpa rasa ketarik, Diperkaya dengan bahan-bahan untuk melembabkan & menghidrasi kulit, Sensitive skin friendly/aman digunakan untuk kulit sensitif (Telah diuji secara Dermatologis)",
            product_category_id=3,
            brand_id=14,
            product_type_detail_id=7,
            ingredient_id=18,
            skin_problem_id=3,
        ),
        Product(
            name="Brighter Skin Barrier Pudding",
            suitable_for="Kulit kusam & berjerawat, bekas jerawat dan hiperpigmentasi",
            key_ingredient="Tranexamic Acid, Turmeric, Pumpkin",
            benefit="Menyamarkan bekas jerawat kemerahan PIE & hiperpigmentasi, Mencerahkan wajah, Memperkuat skin barrier, Menjaga hidrasi serta melembapkan wajah",
            product_category_id=2,
            brand_id=35,
            product_type_detail_id=9,
            ingredient_id=19,
            skin_problem_id=3,
        ),
        Product(
            name="Radiant Glow Jelly Cleanser",
            suitable_for="Kulit kusam, Bekas jerawat kemerahan (PIE), Bekas jerawat kehitaman (PIH), Kulit kotor akibat debu/polusi, Warna kulit tidak merata",
            key_ingredient="Tranexamic Acid, Niacinamide, Kojic Acid, Alpha Arbutin, Glutathione, Melazero, Amino Acid Complex",
            benefit="Membersihkan kotoran secara mendalam tanpa membuat kulit kering, mencerahkan dan meratakan warna kulit, melembutkan dan menyegarkan kulit",
            product_category_id=3,
            brand_id=32,
            product_type_detail_id=6,
            ingredient_id=19,
            skin_problem_id=3,
        ),
        Product(
            name="UV Shield Tinted Tone Up Sunscreen",
            suitable_for="Semua jenis kulit",
            key_ingredient="Tranexamic, Bright-Peptide, Color Correct™",
            benefit="Membantu mencerahkan kulit kusam dan noda hitam secara jangka panjang pemakaian, Memiliki hasil yang smooth, tidak lengket, cepat meresap, dan ringan",
            product_category_id=1,
            brand_id=18,
            product_type_detail_id=12,
            ingredient_id=19,
            skin_problem_id=3,
        ),
        Product(
            name="Glow Booster C-Dose+ Water Moisturizer",
            suitable_for="Kulit kusam, Kulit kering, Warna kulit tidak merata",
            key_ingredient="Vitamin C EAA, Vitamin C NIO-VCS",
            benefit="Membuat kulit tampak lebih cerah dan bercahaya, Merawat elastisitas kulit, Melembabkan dan menutrisi kulit secara mendalam",
            product_category_id=2,
            brand_id=3,
            product_type_detail_id=8,
            ingredient_id=20,
            skin_problem_id=3,
        ),
        Product(
            name="C-defense Vitamin C + Panthenol Anti-Pollution Radiant Creamy Wash",
            suitable_for="Semua jenis kulit, terutama kulit normal dan berminyak",
            key_ingredient="Vitamin C dan Panthenol",
            benefit="Memberikan kesegaran, Membersihkan dan menjaga kelembapan kulit, Mencerahkan, Melindungi dari polusi",
            product_category_id=3,
            brand_id=18,
            product_type_detail_id=5,
            ingredient_id=20,
            skin_problem_id=3,
        ),
        Product(
            name="Hydramax-C Sunscreen Serum",
            suitable_for="Semua jenis kulit terutama kulit normal dan kulit kering",
            key_ingredient="Vitamin C, Hyaluron 11 Multi-complex, Ectoin",
            benefit="Melembabkan dan melindungi kulit dari pengaruh buruk sinar matahari, sinar bluelight dan polusi",
            product_category_id=1,
            brand_id=19,
            product_type_detail_id=12,
            ingredient_id=20,
            skin_problem_id=3,
        ),
        Product(
            name="Triple Care Sunscreen",
            suitable_for="Kulit normal",
            key_ingredient="Hybrid UV Filters, Blue Oleoactif, Niacinamide, White Ten, Tranexamic Acid, CICA, Mugwort & SyriCalm",
            benefit="Memberikan perlindungan terhadap UV A, UV B & Blue Light, mencerahkan wajah, menengankan dan sebagai anti inflamation agents",
            product_category_id=1,
            brand_id=2,
            product_type_detail_id=12,
            ingredient_id=12,
            skin_problem_id=3,
        ),
        Product(
            name="Whitening Night Cream",
            suitable_for="Kulit normal",
            key_ingredient="Shea Butter, Glutathione, Arbutin, Aloe Barbadensis Leaf Extract",
            benefit="Mencerahkan kulit",
            product_category_id=2,
            brand_id=36,
            product_type_detail_id=9,
            ingredient_id=3,
            skin_problem_id=3,
        ),
        Product(
            name="Low pH Gentle Jelly Cleanser",
            suitable_for="Semua jenis kulit, termasuk kulit sensitif",
            key_ingredient="Japanese Mugwort, Tea Tree, Centella Asiatica, Calendula Officinalis, Peppermint",
            benefit="Membersihkan debu, kotoran, & minyak berlebih pada kulit, Menenangkan kulit kembali, Menjaga kulit lebih cerah dan halus, Meminimalisasi terjadinya reaksi sensitisasi",
            product_category_id=2,
            brand_id=1,
            product_type_detail_id=6,
            ingredient_id=11,
            skin_problem_id=3,
        ),
        Product(
            name="Pure Radiance Barrier Moisturizer",
            suitable_for="Kulit normal hingga berminyak, Kulit berjerawat, Minyak berlebih, Pori-pori besar, Jerawat meradang, Bekas jerawat",
            key_ingredient="Actiwhite, Jeju Green Tea Water, Lipo Amino Acids",
            benefit="Memudarkan bekas jerawat, merapatkan pori-pori, mengontrol minyak",
            product_category_id=2,
            brand_id=19,
            product_type_detail_id=8,
            ingredient_id=9,
            skin_problem_id=1,
        ),
    ]

    db.session.add_all(products)
    db.session.commit()
    print("✅ Products seeded successfully.")
